var a = 10;
var b = 20;
var c = 30;
var d = 40;
var e = 50;
var f = 60;
var g = 70;
var h = 80;
var i = 90;
var j = 100;

console.log(a + b);
console.log(c + d);
console.log(a - b);
console.log(c - d);
console.log(j * i);
console.log(e * g);
console.log(g / h);
console.log(f / h);
console.log(a++);
console.log(b++);
console.log(c--);
console.log(d--);
